#!/usr/bin/env bash
# Write a Bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2

i=1
while [ $i -gt 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done
