#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
# Pauses two seconds in between each message.
# Bash Script process to be managed by 101-manage_my_process

i=1
while [ $i -gt 0 ]; do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
