#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# The Bash Script should:
# 1. Displays FizzBuzz when the number is a multiple of 3 and 5
# 2. Displays Fizz when the number is multiple of 3
# 3. Displays Buzz when the number is a multiple of 5
# 4. Otherwise, displays the number in a list format

num=1
while [ $num -le 100 ]; do
	if (( num % 3 == 0 && num % 5 == 0 )); then
                echo "FizzBuzz"
	elif (( num % 3 == 0 )); then
		echo "Fizz"
	elif (( num % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$num"
	fi
	((num++))
done
