#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# The Bash Script should only display:
# username
# user id
# Home directory path for the user

passwd_file="/etc/passwd"
if [ -f "$passwd_file" ]; then
    while IFS=: read -r username password uid gid info home shell; do
        echo "Username: $username"
        echo "User ID: $uid"
        echo "Home Directory: $home"
        echo
    done < "$passwd_file"
else
    echo "The /etc/passwd file does not exist."
fi
