#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file

# awk '{print $1 " " $9}' apache-access.log.

if [ -f "apache-access.log" ]; then
    awk '{print $1, $9}' apache-access.log
else
    echo "The apache-access.log file does not exist."
fi
