#!/usr/bin/env bash
# Prints the phrase "Best school" 10 times but only
#print "Hi" on the nineth iteration instead (while loop).

i=0
while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo "Hi"
	fi
	echo "Best School"
	((i++))
done
