#!/usr/bin/env bash
# Prints "bad luck for the fourth iteration,
# prints "good luck" for the eighth iteration, and
# prints "Best school" for every other iteration
# amounting to 10 iterations in total (while loop).

i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
