#!/usr/bin/env bash
# Bash script that displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed (for loop)

for file in *; do
    if [[ -f $file && $file != .* ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
