#!/usr/bin/env bash
# Bash script that displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed (for loop)

ls | cut -d '-' -f 2-
